{config, ...}: {
  users = {
    # Don't allow mutation of users outside the config.
    mutableUsers = false;

    groups = {
      jhc = {};
    };

    users = {
      jhc = {
        # generated by `mkpasswd -m scrypt`
        # we have to use initialHashedPassword here when using tmpfs for /
        hashedPasswordFile = config.sops.secrets.initialHashedPassword.path;
        home = "/home/jhc";
        isNormalUser = true;
        description = "Jun-Hong Cheng";
        extraGroups = [
          "jhc"
          "users"
          "networkmanager"
          "wheel"
        ];
        openssh.authorizedKeys.keys = [
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKHjmk95MME81Aiz/FoCoD5JOXJtzZkz9A9qmsOmrtI/ qwe854896@Jun-Hongs-MacBook-Air.local"
        ];
      };

      # root's ssh key are mainly used for remote deployment
      root = {
        inherit (config.users.users.jhc) initialHashedPassword;
        openssh.authorizedKeys.keys = config.users.users.jhc.openssh.authorizedKeys.keys;
      };
    };
  };
}
