[files]
ignore-dot = true
ignore-files = true
extend-exclude = ["themes/", "data/", "static-surprises/", "resources/"]

[default]
binary = false
# ignore some special identifiers(sha256, mac address, crypto keys, etc)
extend-ignore-re = [
  "06413w510jmld20i4lik9b36cfafm501864yq8k4vxl5r4hn0j0h" # emacsOverlaySHA256
]
