#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		pkill -9 ${_prs}
	fi
done

# Launch statusbur (waybar)
bash ~/.config/hypr/scripts/statusbar &
