# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "xhci_pci" "sr_mod" "virtio_blk"];
      kernelModules = [];
    };

    kernelModules = ["kvm-intel"];
    extraModulePackages = [];

    # clear /tmp on boot to get a stateless /tmp directory.
    tmp.cleanOnBoot = true;
  };

  fileSystems = {
    # equal to `mount -t tmpfs tmpds /`
    "/" = {
      device = "tmpfs";
      fsType = "tmpfs";
      # set mode to 755, otherwise systemd will set it to 777, which causes problems
      # relatime: update inode access times relative to modify or change time.
      options = ["relatime" "mode=755"];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/1fff006e-2419-4259-82c3-6d9a423e33b5";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/350C-267B";
      fsType = "vfat";
      options = ["fmask=0022" "dmask=0022"];
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/9a761cd2-c9a6-4c94-9910-3cbd05871802";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
