{config, ...}: {
  users = {
    # Don't allow mutation of users outside the config.
    mutableUsers = false;

    groups = {
      jhc = {};
    };

    users = {
      jhc = {
        # generated by `mkpasswd -m scrypt`
        # we have to use hashed password here when using tmpfs for /
        initialHashedPassword = "$7$CU..../....c8s4IqMoRtRsI13q11KZI0$djwyCmk7V.MJW5EfAK1pJGbekV./VZfTrt2BczEYMF1";
        home = "/home/jhc";
        isNormalUser = true;
        description = "Jun-Hong Cheng";
        extraGroups = [
          "jhc"
          "users"
          "networkmanager"
          "wheel"
          # "docker"
        ];
        openssh.authorizedKeys.keys = [
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICulqU2bsFu8qMXLKBD+ZZEis+HVLZ5hTYKCnkbi4zZr jhc@mba"
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDcGrsoMSheEGxr/n8EIM9yi4A7B8osOS6HxHxzS+VGs jhc@ios"
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJNeNtX9kuPIcPX4EZGtBzXoYRo1HLDCpwP7dzTHNfra jhc@siber"
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP2xOjSBwDVRGgI1yZy9P6G2jhV4mP9UV13HDNP5qQVr jhc@tuxedo"
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB5UJuezTHnw7Ag7bbVviudSF23lY6x4mIb6sS321U52 kieann.cs13@nycu.edu.tw"
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPbRhCz+zKPCnvLdvPJb9R+IeXDStN7DB3k7H+wyBRTF drvoc4do@bitwarden"
        ];
      };

      # root's ssh key are mainly used for remote deployment
      root = {
        inherit (config.users.users.jhc) hashedPasswordFile;
        openssh.authorizedKeys.keys = config.users.users.jhc.openssh.authorizedKeys.keys;
      };
    };
  };
}
